# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rdpl}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["C\303\241ssio Marques"]
  s.date = %q{2010-09-24}
  s.description = %q{RDPL provides a way to create labels for the Datamax™ printers using plain Ruby, through an abstraction of the DPL (Datamax Programming Language)}
  s.email = %q{cassiommc@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rvmrc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/elements/barcode.rb",
     "lib/elements/bitmapped_text.rb",
     "lib/elements/box.rb",
     "lib/elements/element.rb",
     "lib/elements/graphic.rb",
     "lib/elements/line.rb",
     "lib/elements/lines_and_boxes.rb",
     "lib/job.rb",
     "lib/label.rb",
     "lib/rdpl.rb",
     "rdpl.gemspec",
     "spec/elements/barcode_spec.rb",
     "spec/elements/bitmapped_text_spec.rb",
     "spec/elements/box_spec.rb",
     "spec/elements/line_spec.rb",
     "spec/job_spec.rb",
     "spec/label_spec.rb",
     "spec/rdpl_spec.rb",
     "spec/shared_examples/element.rb",
     "spec/shared_examples/lines_and_boxes.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/cassiomarques/rdpl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Create Datamax™ labels using Ruby!}
  s.test_files = [
    "spec/elements/barcode_spec.rb",
     "spec/elements/bitmapped_text_spec.rb",
     "spec/elements/box_spec.rb",
     "spec/elements/line_spec.rb",
     "spec/job_spec.rb",
     "spec/label_spec.rb",
     "spec/rdpl_spec.rb",
     "spec/shared_examples/element.rb",
     "spec/shared_examples/lines_and_boxes.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

